package com.example.labOdc.Enum;

public enum Permission {
    SYSTEM_MANAGE_USERS,
    SYSTEM_ASSIGN_ROLE,
    SYSTEM_MANAGE_SETTINGS,
    SYSTEM_MANAGE_TEMPLATES,
    SYSTEM_VIEW_AUDIT_LOG,
    SYSTEM_FORCE_LOGOUT,

    /* ================= LAB ADMIN ================= */
    LAB_APPROVE_COMPANY,
    LAB_SUSPEND_COMPANY,
    LAB_VALIDATE_PROJECT,
    LAB_PUBLISH_PROJECT,
    LAB_INVITE_MENTOR,
    LAB_ASSIGN_MENTOR,
    LAB_APPROVE_PAYMENT,
    LAB_ALLOCATE_FUND,
    LAB_ADVANCE_FUND,
    LAB_APPROVE_DISTRIBUTION,
    LAB_VIEW_ALL_REPORTS,
    LAB_RECORD_RISK,
    LAB_APPROVE_CHANGE,
    LAB_VIEW_ALL_DATA,

    /* ================= COMPANY ================= */
    COMPANY_MANAGE_PROFILE,
    COMPANY_CREATE_PROJECT,
    COMPANY_SUBMIT_PROJECT,
    COMPANY_VIEW_OWN_PROJECT,
    COMPANY_MAKE_PAYMENT,
    COMPANY_REQUEST_CHANGE,
    COMPANY_CANCEL_PROJECT,
    COMPANY_EVALUATE,

    /* ================= MENTOR ================= */
    MENTOR_MANAGE_PROFILE,
    MENTOR_ACCEPT_INVITE,
    MENTOR_REVIEW_TALENT,
    MENTOR_APPROVE_APPLICATION,
    MENTOR_ASSIGN_TASK,
    MENTOR_REVIEW_TASK,
    MENTOR_SUBMIT_REPORT,
    MENTOR_CONFIRM_FUND,
    MENTOR_EVALUATE,

    /* ================= TALENT ================= */
    TALENT_MANAGE_PROFILE,
    TALENT_APPLY_PROJECT,
    TALENT_WITHDRAW_APPLICATION,
    TALENT_VIEW_ASSIGNED_TASK,
    TALENT_UPDATE_TASK,
    TALENT_COMMENT_TASK,
    TALENT_VIEW_FUND,
    TALENT_EVALUATE,

    /* ================= TALENT LEADER (CONTEXT) ================= */
    LEADER_DISTRIBUTE_FUND,
    LEADER_SUBMIT_TEAM_REPORT,
    LEADER_REPRESENT_TEAM,
    LEADER_VOTE
}
